### ISSUE TITLE
Check for technical exclusive-or business error needs reworking

### ISSUE THREAD

**Issue by BLangendorf** [killbill/killbill-adyen-plugin#25]
The xor check in [AdyenPaymentTransactionInfoPlugin.java#L123](https://github.com/killbill/killbill-adyen-plugin/blob/master/src/main/java/org/killbill/billing/plugin/adyen/api/AdyenPaymentTransactionInfoPlugin.java#L123) …
```
checkArgument(adyenCallErrorStatus.isPresent() ^ pspResult.isPresent());
```
… will always fail for the call at [AdyenPaymentTransactionInfoPlugin.java#L95-L98](https://github.com/killbill/killbill-adyen-plugin/blob/master/src/main/java/org/killbill/billing/plugin/adyen/api/AdyenPaymentTransactionInfoPlugin.java#L95-L98) …
```
getPaymentPluginStatus(Optional.of(AdyenCallErrorStatus.UNKNOWN_FAILURE),
                       Optional.of(PaymentServiceProviderResult.getPaymentResultForId(record.getPspResult())))
```
… because `Optional.of(...)` never returns `.absent()` but rather throws a `NullPointerException` when called with `null`: [Optional.java#L83-L88](https://code.google.com/p/guava-libraries/source/browse/guava/src/com/google/common/base/Optional.java?r=806967c3660d231e62a52674703acb51ec4e6623#83).

**Comment by pierre** [comment]
Note that [AdyenPaymentTransactionInfoPlugin.java#L95-L98](https://github.com/killbill/killbill-adyen-plugin/blob/master/src/main/java/org/killbill/billing/plugin/adyen/api/AdyenPaymentTransactionInfoPlugin.java#L95-L98) breaks [getPaymentInfo](https://github.com/killbill/killbill-plugin-api/blob/master/payment/src/main/java/org/killbill/billing/payment/plugin/api/PaymentPluginApi.java#L144), as the `PaymentTransactionInfoPlugin` returned won't match the one returned by the payment API call.

The underlying problem is that we are not storing the information about the technical error, so we cannot re-build it.

Looking at how Ruby plugins do it, they actually store the exception and the computed plugin status [in the response row](https://github.com/killbill/killbill-plugin-framework-ruby/blob/master/lib/killbill/helpers/active_merchant/gateway.rb#L141), which is then re-used in the get path for both the [status](https://github.com/killbill/killbill-plugin-framework-ruby/blob/master/lib/killbill/helpers/active_merchant/active_record/models/response.rb#L116-L124) and the [error message](https://github.com/killbill/killbill-plugin-framework-ruby/blob/master/lib/killbill/helpers/active_merchant/active_record/models/response.rb#L135-L136) (associated [unit tests](https://github.com/killbill/killbill-plugin-framework-ruby/blob/master/spec/killbill/helpers/payment_plugin_spec.rb#L459-L461) and [integration tests](https://github.com/killbill/killbill-integration-tests/blob/master/killbill-integration-tests/plugins/payment/errors-handling/test_plugins_error_handling.rb#L77)). We probably need to do something similar here (maybe we can re-use the generic `additional_data` column, which is already assumed to contain JSON?).

```
MariaDB [killbill]> select distinct message from cybersource_responses;
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| message                                                                                                                                                             |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| {"exception_class":"ActiveMerchant::ResponseError","exception_message":"Failed with 302 Found","payment_plugin_status":"UNDEFINED"}                                 |
| {"exception_class":"ActiveMerchant::ResponseError","exception_message":"Failed with 404 Not Found ","payment_plugin_status":"UNDEFINED"}                            |
| {"exception_class":"ActiveMerchant::ResponseError","exception_message":"Failed with 500 Internal Server Error","payment_plugin_status":"UNDEFINED"}                 |
| {"exception_class":"ActiveMerchant::RetriableConnectionError","exception_message":"The remote server refused the connection","payment_plugin_status":"UNDEFINED"}   |
| {"exception_class":"EOFError","exception_message":"End of file reached","payment_plugin_status":"UNDEFINED"}                                                        |
| {"exception_class":"Errno::ECONNREFUSED","exception_message":"Connection refused - Connection refused","payment_plugin_status":"CANCELED"}                          |
| {"exception_class":"Errno::ECONNRESET","exception_message":"Connection reset by peer - Connection reset by peer","payment_plugin_status":"UNDEFINED"}               |
| {"exception_class":"Errno::EPIPE","exception_message":"Broken pipe - Broken pipe","payment_plugin_status":"UNDEFINED"}                                              |
| {"exception_class":"IOError","exception_message":"Unsupported record version Unknown-79.84","payment_plugin_status":"UNDEFINED"}                                    |
| {"exception_class":"IOError","exception_message":"Unsupported record version Unknown-84.84","payment_plugin_status":"UNDEFINED"}                                    |
| {"exception_class":"OpenSSL::SSL::SSLError","exception_message":"Broken pipe","payment_plugin_status":"CANCELED"}                                                   |
| {"exception_class":"OpenSSL::SSL::SSLError","exception_message":"Connection reset by peer","payment_plugin_status":"CANCELED"}                                      |
| {"exception_class":"OpenSSL::SSL::SSLError","exception_message":"Socket closed","payment_plugin_status":"CANCELED"}                                                 |
| {"exception_class":"OpenSSL::SSL::SSLError","exception_message":"Unrecognized SSL message, plaintext connection?","payment_plugin_status":"CANCELED"}               |
| {"exception_class":"OpenSSL::SSL::SSLError","exception_message":"Unsupported record version Unknown-84.84","payment_plugin_status":"CANCELED"}                      |
| {"exception_class":"OpenSSL::SSL::SSLError","exception_message":"hostname does not match the server certificate","payment_plugin_status":"CANCELED"}                |
| {"exception_class":"OpenSSL::SSL::SSLError","exception_message":"signed overrun, bytes = 108","payment_plugin_status":"CANCELED"}                                   |
| {"exception_class":"OpenSSL::SSL::SSLError","exception_message":"writer side was already closed.","payment_plugin_status":"CANCELED"}                               |
| {"exception_class":"SocketError","exception_message":"initialize: name or service not known","payment_plugin_status":"CANCELED"}                                    |
| {"exception_class":"Timeout::Error","exception_message":"Timeout::Error","payment_plugin_status":"UNDEFINED"}                                                       |
| {"exception_class":"Timeout::Error","exception_message":"execution expired","payment_plugin_status":"UNDEFINED"}                                                    |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

Related issue: https://github.com/killbill/killbill-adyen-plugin/issues/22.

**Comment by arnelandwehr** [comment]
bug could be solved with Optional.ofNullable(). If the JavaDoc on the method is not enough to explain the check we should extend it.
